name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Grunt CLI and dependencies
      run: |
        npm install -g grunt-cli
        npm install
        npm install grunt --save-dev  # 本地安装 grunt

    - name: Run Grunt
      run: |
        grunt

    - name: Set up Node.js environment (optional settings)
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        always-auth: false
        architecture: x64
        check-latest: true
        registry-url: "https://registry.npmjs.org"
        scope: ""
        token: ${{ secrets.GITHUB_TOKEN }}
        cache: "npm"
        cache-dependency-path: "package-lock.json"
