name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
npm install -g grunt-cli
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies and run Grunt
      run: |
        npm install
        grunt

    - name: Set up Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        always-auth: false  # Optional, set to true if always-auth is needed
        architecture: x64  # Optional, specify target architecture
        check-latest: true  # Optional, use latest available matching version
        registry-url: "https://registry.npmjs.org"  # Optional registry URL for authentication
        scope: ""  # Optional, for scoped registries if needed
        token: ${{ secrets.GITHUB_TOKEN }}  # Optional, token for GitHub registry access
        cache: "npm"  # Optional, specify package manager for caching (e.g., npm, yarn, pnpm)
        cache-dependency-path: "package-lock.json"  # Optional, path to dependency lock file
