name: Node.js CI with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install
        npm install grunt-cli --save-dev

    - name: Run Grunt tasks
      run: |
        grunt

    - name: Upload artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: dist-files
        path: dist/

    - name: Set Telegram Webhook
      if: success()  # 确保在构建成功后执行
      run: |
        curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/setWebhook" \
             -d url="https://stonle.com:8443/telegram-webhook/19941221"
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
